export const tourScenes = [
  {
    id: "punto-01",
    label: "Punto 01",
    title: "Acceso y circulación",
    description: "Primer punto de orientación dentro del recorrido virtual.",
    imageSource: "/tour/recorrido/panorama-01.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 38,
    previousYaw: null,
  },
  {
    id: "punto-02",
    label: "Punto 02",
    title: "Pasillo técnico",
    description: "Vista de circulación entre las áreas de trabajo del laboratorio.",
    imageSource: "/tour/recorrido/panorama-02.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 38,
    previousYaw: -150,
  },
  {
    id: "punto-03",
    label: "Punto 03",
    title: "Área analítica",
    description: "Recorrido visual por una zona de instrumentación y análisis.",
    imageSource: "/tour/recorrido/panorama-03.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 35,
    previousYaw: -140,
  },
  {
    id: "punto-04",
    label: "Punto 04",
    title: "Instrumentación",
    description: "Punto de observación de equipamiento y estaciones de laboratorio.",
    imageSource: "/tour/recorrido/panorama-04.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 35,
    previousYaw: -130,
  },
  {
    id: "punto-05",
    label: "Punto 05",
    title: "Estación de trabajo",
    description: "Área de trabajo incluida en la ruta de exploración virtual.",
    imageSource: "/tour/recorrido/panorama-05.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 35,
    previousYaw: -130,
  },
  {
    id: "punto-06",
    label: "Punto 06",
    title: "Área de análisis",
    description: "Último punto del recorrido por las instalaciones del laboratorio.",
    imageSource: "/tour/recorrido/panorama-06.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: null,
    previousYaw: -130,
  },
] as const;

export type TourScene = (typeof tourScenes)[number];
export type TourSceneId = TourScene["id"];
