export const tourScenes = [
  {
    id: "punto-01",
    label: "Punto 01",
    title: "Acceso y circulacion",
    description: "Primer punto de orientacion dentro del recorrido virtual.",
    imageSource: "/tour/recorrido/panorama-01.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 38,
    previousYaw: null,
  },
  {
    id: "punto-02",
    label: "Punto 02",
    title: "Pasillo tecnico",
    description: "Vista de circulacion entre las areas de trabajo del laboratorio.",
    imageSource: "/tour/recorrido/panorama-02.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 38,
    previousYaw: -150,
  },
  {
    id: "punto-03",
    label: "Punto 03",
    title: "Area analitica",
    description: "Recorrido visual por una zona de instrumentacion y analisis.",
    imageSource: "/tour/recorrido/panorama-03.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 35,
    previousYaw: -140,
  },
  {
    id: "punto-04",
    label: "Punto 04",
    title: "Instrumentacion",
    description: "Punto de observacion de equipamiento y estaciones de laboratorio.",
    imageSource: "/tour/recorrido/panorama-04.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 35,
    previousYaw: -130,
  },
  {
    id: "punto-05",
    label: "Punto 05",
    title: "Estacion de trabajo",
    description: "Area de trabajo incluida en la ruta de exploracion virtual.",
    imageSource: "/tour/recorrido/panorama-05.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: 35,
    previousYaw: -130,
  },
  {
    id: "punto-06",
    label: "Punto 06",
    title: "Area de analisis",
    description: "Ultimo punto del recorrido por las instalaciones del laboratorio.",
    imageSource: "/tour/recorrido/panorama-06.jpg",
    yaw: 0,
    pitch: 0,
    nextYaw: null,
    previousYaw: -130,
  },
] as const;

export type TourScene = (typeof tourScenes)[number];
export type TourSceneId = TourScene["id"];
